@startuml
[OrderManagementService]
[UserManagementService]
[ShipmentService]
[CatalogService]

[OrderManagementService] --> [CatalogService]
[ShipmentService] --> [UserManagementService]
[ShipmentService] --> [CatalogService]

@enduml